### ISSUE TITLE
EnterpriseSearch API error: Indexing Date error. (Possibly type coercion)

### ISSUE THREAD

**Issue by n8-dev** [silverstripeltd/silverstripe-forager#26]
## Module version

Which tagged version (or commit hash) are you using?
`silverstripe/silverstripe-search-sdk` : `2.2.0`

∴ `silverstripe-forager` : `1.1.1`

## Problem statement

A property that is defined in yaml with `options: type: date` will break on the indexing when its DB value is `NULL`.

It appears to get converted into `''` and you get the following error in the job.

```
EnterpriseSearch API error: Array ( 
  [0] => [1:539] failed to parse field [effective_date] of type [date] in document with id 'namespace_to_class_14'.
Preview of field's value: '',
```

<details>

<summary>Old context that is no longer exactly relevant</summary>

Something seems to be passing in `''` into a Date field when indexing when it should be a `null`.

As per other fields you'd assume that it would just not create an entry.

Unfortunately in the jobs you get a lot of errors like this.

```bash
[2025-05-30 15:47:46][ERROR] EnterpriseSearch API error: Array ( 
  [0] => [1:539] failed to parse field [effective_date]
of type [date] in document with id 'namespace_to_class_14'.
Preview of field's value: '',
...
```

## Steps to reproduce

Take the following set up. 

```yaml
SilverStripe\Forager\Service\IndexConfiguration:
...
        ParentClass:
...
            effective_date:
              property: EffectiveDate
              options:
                type: date



ParentClass:
  extensions:
    search: SilverStripe\Forager\Extensions\SearchServiceExtension
```

`SilverStripe\Forager\Extensions\SearchServiceExtension` is attached to 

```php


ParentClass extends DataObject
{
  ...
}


ChildClass extends DataObject
{

private static $db = [
  'EffectiveDate' => 'Date',
];


}
```

You'd assume that you'd get a bunch of `record_base_class`: `ParentClass` and a mix of `source_class` as `ParentClass` and `ChildClass`.

And the only ones with a value in `effective_date` are `ChildClass`.

However the error happens, breaking all the jobs, and the only items seeming to end up in the index are the `ChildClass`

I even tried specifically forcing `null` to return by using a custom method on `ParentClass`

```php
public function getEffectiveDateForSearch(): ?DBDatetime
    {
        if ($this->hasField('EffectiveDate')) {
            return $this->EffectiveDate == null ? null : DBDatetime::create()->setValue($this->EffectiveDate);
        }

        return null;
    }
```

Tested the function, and it performs as expected with various data, however still getting the same `EnterpriseSearch API error`

</details>

**Comment by GuySartorelli** [comment]
> It appears to get converted into '' and you get the following error in the job.

Note that this is correctly being returned as `null` by the ORM - just to rule out that red herring.

**Comment by n8-dev** [comment]
Yeah, what's strange is all other fields work fine, its just the `Date` being null Elastic provider module bugs out. :(

**Comment by blueo** [comment]
@n8-dev could you tell me how you're getting the value for your date field? I did a bit of testing and if I setup a db field eg:

```PHP
    private static array $db = [
        'Nothing' => DBDatetime::class,
    ];
```

And if this has no value - then value will default to `1970-01-01T00:00:00+00:00` when sent to the service. I guess you're using another method to retrieve this value? 
Atm this looks like a bug as we'd ideally have a better way of dealing with null values (options include not sending the value at all down to some api handling).

**Comment by blueo** [comment]
oh I think I see now. The date field is only on child class so I think you have two options:

1. add your search config only on the child class eg

```YAML
SilverStripe\Forager\Service\IndexConfiguration:
...
        ParentClass:
            #other fields here
...
        ChildClass:
            effective_date:
              property: EffectiveDate
              options:
                type: date
```

1. or define a method on your parent class to return a valid date on your parent class eg:

```PHP
public function getEffectiveDate(): string|DBDate
    {
        if ($this->hasField('EffectiveDate')) {
            return $this->EffectiveDate;
        }

        return DBDate::singleton()->Rfc3339();
    }
```

or some equivalent of that.
