### ISSUE TITLE
Add an explicit error if an invalid yaml format is detected

### ISSUE THREAD

**Issue by chrispenny** [silverstripeltd/silverstripe-forager#7]
This is the correct format, whereby you can set `options.type: number`:
```
SilverStripe\Forager\Service\IndexConfiguration:
  indexes:
    main:
      includeClasses:
        SilverStripe\CMS\Model\SiteTree:
          fields:
            title: true
            parent_id:
              property: ParentID
              options:
                type: number
```

If a developer accidentally forgets the `options` parent object, then there is no error to indicate that something is about to go wrong, and that they will be about to define their field as `type: text` (or whatever the default field type is for the plugin module).

EG: This is an incorrect format, which will result in an unexpected field type:
```
SilverStripe\Forager\Service\IndexConfiguration:
  indexes:
    main:
      includeClasses:
        SilverStripe\CMS\Model\SiteTree:
          fields:
            title: true
            parent_id:
              property: ParentID
              type: number
```
